/*
 * Generated by MTK SP DrvGen Version: 3.5.160809 for MT6797.
 * 2019-10-15 18:15:47
 * Do Not Modify The File.
 * Copyright Mediatek Inc. (c) 2016.
*/

#ifndef __CUST_POWER_H
#define __CUST_POWER_H

#define GPIO_DVDD28_MC1		GPIO_VMC
#define GPIO_DVDD28_SIM		GPIO_VIO18
#define GPIO_DVDD28_SIM2		GPIO_VIO18


#endif /* __CUST_POWER_H */
